version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    container_name: nestjs
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  data:
